[spice]
; host ip address
; password is optional but recommended, set to default
; Host = localhost
Host = 192.168.1.X
Port = 57300
Password = changeme

[cards]
; Replace with your card and pin
card = 012E111111111111
pin = "1234"

; if you want to use 2 player
card2 = 012E111111111111
pin2 = "1234"

; If you (first card) are P2 set this to 1
P = 0
